fix: 🐛 Login Screen "TypeError"
TypeError: null: type 'Null' is Not a subtype of type widget, the error
is because of usage of old version of Flutter  features like Raised
Button on the place of Elevated Button and Outline button on the place
of OUTLINED button

BREAKING CHANGE: 🧨 Version update, Packege Update and project cleaning, Project name
change. need to rebuild the entire project if breaks the code